### ISSUE TITLE
problem installing ideal 

### ISSUE THREAD

**Issue by sopenaml** [federicomarini/ideal_serveredition#1]
Hi,

I've tried to follow the instructions for your package and I'm struggling with it. It says, 

Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘RMySQL’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘GenomicFeatures’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘geneLenDataBase’ had non-zero exit status
4: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘goseq’ had non-zero exit status
5: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘ideal’ had non-zero exit status
> install.packages("ideal", dependencies=TRUE)
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning message:
package ‘ideal’ is not available (for R version 3.4.1) 

If I try instead to run  install.packages("ideal", dependencies=TRUE)
as I have seen in forums as a solution for the warning above, I still get the same error as above. 
nstalling package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
Warning message:
package ‘ideal’ is not available (for R version 3.4.1) 

Any help would be greatly appreciated.

Here's my sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 24 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.28.0

loaded via a namespace (and not attached):
[1] compiler_3.4.1 tools_3.4.1    tcltk_3.4.1

**Comment by federicomarini** [comment]
Hi,
this looks like it is not directly related to the `ideal` package but rather to `RMySQL`, which with its failure in installation brings then down the dependency chain.
Did you try more recently again? I am asking since on both of my devel machines I was not able to reproduce the error.
F
