### ISSUE TITLE
Option to download DE Genes table

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/ideal_serveredition#5]
Hi

On the ideal shiny app, is there an option to download the DEGs table on the "Extract Results" tab after the DE identification is complete?

After performing action "Extract the results", I thought clicking  "store current results" would have given a pop-up to save the DEGs identified, but nothing happened - probably that's not the intent of "store current results"?

![image](https://user-images.githubusercontent.com/8467214/97253811-769dcc00-17e3-11eb-99a3-1476ff9331b3.png)

**Comment by federicomarini** [comment]
Actually this should be feasible via the button below the DE table.
Can you check whether this works?

**Comment by tamuanand** [comment]
Hi @federicomarini 

Yes - one can download the table using the button -- but it downloads the entire table. One has to open the csv/table in excel and filter the padj column to <= 0.05 (or whatever was used by the user)

Hence I was wondering if a separate button can be provided that will download only the DEGs

Note - this is not a showstopper/deal-breaker - just suggesting some features

**Comment by federicomarini** [comment]
Oh ok, sorry I misread your initial message.
After some initial feedback rounds with colleagues and cooperation partners, we opted deliberately for giving the whole table, and rather leave to the user the task to subset it. The design principle was to not clutter too much the UI

**Comment by tamuanand** [comment]
Thanks a  lot - I will close the issue
