### ISSUE TITLE
Unable to generate report preview with markdown options

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/ideal_serveredition#7]
Hi

I am unable to have the Report Preview generated  - SessionInfo is the same as reported in https://github.com/federicomarini/ideal_serveredition/issues/6 

The last few lines in the log are something like below (though I think they are unrelated to the report preview error)

```
Warning in grDevices::png(f) : failed to load cairo DLL
Warning in (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  :
  failed to load cairo DLL
Quitting from lines 17-22 ()
Warning: Error in dev.control: dev.control() called without an open graphics device
  123: stop
  122: dev.control
  121: chunk_device
  120: block_exec
  119: call_block
  118: process_group.block
  115: process_file
  114: knit
  113: knit2html
   96: renderUI
   95: func
   82: origRenderFunc
   81: output$knitDoc
    1: runApp
```

![image](https://user-images.githubusercontent.com/8467214/97380163-db692d00-189c-11eb-9fa5-537ddb930c70.png)

**Comment by federicomarini** [comment]
Hi,
the error message seems to suggest it is an error of the machine where the app is installed - namely, the cairo DLL are not loaded.
I would try reinstalling them compiling from source.
HTH,
Federico

**Comment by tamuanand** [comment]
Hi 

I reinstalled/compiled cairo and this now works. 

However, the UpSetList.pdf generation still is having problems as listed in https://github.com/federicomarini/ideal_serveredition/issues/6
